apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  labels:
    app.kubernetes.io/name: leaderworkerset
    app.kubernetes.io/instance: leaderworkerset-sample
    app.kubernetes.io/part-of: lws
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: lws
  name: leaderworkerset-sample
spec:
  rolloutStrategy:
    rollingUpdateConfiguration:
      maxUnavailable: 2
      maxSurge: 0
  replicas: 7
  leaderWorkerTemplate:
    size: 3
    restartPolicy: Default
    leaderTemplate:
      metadata:
        labels:
          role: "leade"
      spec:
        containers:
        - name: nginx
          image: nginx:1.16.1
          # image: nginx:1.14.2
          resources:
            limits:
              cpu: "100m"
            requests:
              cpu: "50m"
          ports:
          - containerPort: 8080
    workerTemplate:
      metadata:
        labels:
          role: "workr"
      spec:
        containers:
        - name: nginx
          image: nginx:1.16.1
          # image: nginx:1.14.2
          resources:
            limits:
              cpu: "100m"
            requests:
              cpu: "50m"
          ports:
          - containerPort: 8080
